Fix PHPStan baseline generation
Closes #92

diff --git a/commands/web/phpstan b/commands/web/phpstan
--- a/commands/web/phpstan
+++ b/commands/web/phpstan
@@ -16,4 +16,15 @@ test -e phpstan.neon || curl -OL https://git.drupalcode.org/project/gitlab_templ
 sed -i 's/BASELINE_PLACEHOLDER/phpstan-baseline.neon/g' phpstan.neon
 # Add an empty baseline file to ensure it exists.
 test -e phpstan-baseline.neon || touch phpstan-baseline.neon
-phpstan analyse $DDEV_DOCROOT/modules/custom "$@"
+
+CONTRIB_MODULE_DIR=$(find "$DDEV_DOCROOT/modules/custom" -mindepth 1 -maxdepth 1 -type d | head -n 1)
+if [ -n "$CONTRIB_MODULE_DIR" ]; then
+  cd "$CONTRIB_MODULE_DIR"
+  # Ensure PHPStan configuration is symlinked from project root.
+  ln -s ../../../../phpstan.neon 2>/dev/null || true
+  ln -s ../../../../phpstan-baseline.neon 2>/dev/null || true
+  phpstan analyze . "$@"
+else
+  echo "The contrib module directory could not be identified in $DDEV_DOCROOT/modules/custom"
+  exit 1
+fi
